manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: kikangh
      url-base: https://github.com/Kikangh
  projects:
    - name: zmk
      remote: kikangh
      revision: CiZ_V2-HM-Mouse-Display
      import: app/west.yml
  self:
    path: config
